package sn.edu.ugb.grade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BaremeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeAllPropertiesEquals(Bareme expected, Bareme actual) {
        assertBaremeAutoGeneratedPropertiesEquals(expected, actual);
        assertBaremeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeAllUpdatablePropertiesEquals(Bareme expected, Bareme actual) {
        assertBaremeUpdatableFieldsEquals(expected, actual);
        assertBaremeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeAutoGeneratedPropertiesEquals(Bareme expected, Bareme actual) {
        assertThat(actual)
            .as("Verify Bareme auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeUpdatableFieldsEquals(Bareme expected, Bareme actual) {
        assertThat(actual)
            .as("Verify Bareme relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getTotalPoints()).as("check totalPoints").isEqualTo(expected.getTotalPoints()))
            .satisfies(a -> assertThat(a.getExamenId()).as("check examenId").isEqualTo(expected.getExamenId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBaremeUpdatableRelationshipsEquals(Bareme expected, Bareme actual) {
        // empty method
    }
}
