package sn.edu.ugb.grade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResultatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAllPropertiesEquals(Resultat expected, Resultat actual) {
        assertResultatAutoGeneratedPropertiesEquals(expected, actual);
        assertResultatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAllUpdatablePropertiesEquals(Resultat expected, Resultat actual) {
        assertResultatUpdatableFieldsEquals(expected, actual);
        assertResultatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatAutoGeneratedPropertiesEquals(Resultat expected, Resultat actual) {
        assertThat(actual)
            .as("Verify Resultat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatUpdatableFieldsEquals(Resultat expected, Resultat actual) {
        assertThat(actual)
            .as("Verify Resultat relevant properties")
            .satisfies(a -> assertThat(a.getNoteObtenue()).as("check noteObtenue").isEqualTo(expected.getNoteObtenue()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getExamenId()).as("check examenId").isEqualTo(expected.getExamenId()))
            .satisfies(a -> assertThat(a.getDossierId()).as("check dossierId").isEqualTo(expected.getDossierId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatUpdatableRelationshipsEquals(Resultat expected, Resultat actual) {
        // empty method
    }
}
