package sn.edu.ugb.student.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DossierEtudiantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierEtudiantAllPropertiesEquals(DossierEtudiant expected, DossierEtudiant actual) {
        assertDossierEtudiantAutoGeneratedPropertiesEquals(expected, actual);
        assertDossierEtudiantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierEtudiantAllUpdatablePropertiesEquals(DossierEtudiant expected, DossierEtudiant actual) {
        assertDossierEtudiantUpdatableFieldsEquals(expected, actual);
        assertDossierEtudiantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierEtudiantAutoGeneratedPropertiesEquals(DossierEtudiant expected, DossierEtudiant actual) {
        assertThat(actual)
            .as("Verify DossierEtudiant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierEtudiantUpdatableFieldsEquals(DossierEtudiant expected, DossierEtudiant actual) {
        assertThat(actual)
            .as("Verify DossierEtudiant relevant properties")
            .satisfies(a -> assertThat(a.getMatricule()).as("check matricule").isEqualTo(expected.getMatricule()))
            .satisfies(a -> assertThat(a.getNationalite()).as("check nationalite").isEqualTo(expected.getNationalite()))
            .satisfies(a -> assertThat(a.getDateNaissance()).as("check dateNaissance").isEqualTo(expected.getDateNaissance()))
            .satisfies(a -> assertThat(a.getProfilId()).as("check profilId").isEqualTo(expected.getProfilId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierEtudiantUpdatableRelationshipsEquals(DossierEtudiant expected, DossierEtudiant actual) {
        // empty method
    }
}
