package sn.edu.ugb.teacher.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClasseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClasseAllPropertiesEquals(Classe expected, Classe actual) {
        assertClasseAutoGeneratedPropertiesEquals(expected, actual);
        assertClasseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClasseAllUpdatablePropertiesEquals(Classe expected, Classe actual) {
        assertClasseUpdatableFieldsEquals(expected, actual);
        assertClasseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClasseAutoGeneratedPropertiesEquals(Classe expected, Classe actual) {
        assertThat(actual)
            .as("Verify Classe auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClasseUpdatableFieldsEquals(Classe expected, Classe actual) {
        assertThat(actual)
            .as("Verify Classe relevant properties")
            .satisfies(a -> assertThat(a.getNomClasse()).as("check nomClasse").isEqualTo(expected.getNomClasse()))
            .satisfies(a -> assertThat(a.getAnneeScolaire()).as("check anneeScolaire").isEqualTo(expected.getAnneeScolaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClasseUpdatableRelationshipsEquals(Classe expected, Classe actual) {
        // empty method
    }
}
