package sn.edu.ugb.reporting.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class IndicateurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicateurAllPropertiesEquals(Indicateur expected, Indicateur actual) {
        assertIndicateurAutoGeneratedPropertiesEquals(expected, actual);
        assertIndicateurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicateurAllUpdatablePropertiesEquals(Indicateur expected, Indicateur actual) {
        assertIndicateurUpdatableFieldsEquals(expected, actual);
        assertIndicateurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicateurAutoGeneratedPropertiesEquals(Indicateur expected, Indicateur actual) {
        assertThat(actual)
            .as("Verify Indicateur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicateurUpdatableFieldsEquals(Indicateur expected, Indicateur actual) {
        assertThat(actual)
            .as("Verify Indicateur relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getValeur()).as("check valeur").isEqualTo(expected.getValeur()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertIndicateurUpdatableRelationshipsEquals(Indicateur expected, Indicateur actual) {
        // empty method
    }
}
