package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NiveauAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNiveauAllPropertiesEquals(Niveau expected, Niveau actual) {
        assertNiveauAutoGeneratedPropertiesEquals(expected, actual);
        assertNiveauAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNiveauAllUpdatablePropertiesEquals(Niveau expected, Niveau actual) {
        assertNiveauUpdatableFieldsEquals(expected, actual);
        assertNiveauUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNiveauAutoGeneratedPropertiesEquals(Niveau expected, Niveau actual) {
        assertThat(actual)
            .as("Verify Niveau auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNiveauUpdatableFieldsEquals(Niveau expected, Niveau actual) {
        assertThat(actual)
            .as("Verify Niveau relevant properties")
            .satisfies(a -> assertThat(a.getLibelle()).as("check libelle").isEqualTo(expected.getLibelle()))
            .satisfies(a -> assertThat(a.getOrdre()).as("check ordre").isEqualTo(expected.getOrdre()))
            .satisfies(a -> assertThat(a.getProgrammeId()).as("check programmeId").isEqualTo(expected.getProgrammeId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNiveauUpdatableRelationshipsEquals(Niveau expected, Niveau actual) {
        // empty method
    }
}
