package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProgrammeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgrammeAllPropertiesEquals(Programme expected, Programme actual) {
        assertProgrammeAutoGeneratedPropertiesEquals(expected, actual);
        assertProgrammeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgrammeAllUpdatablePropertiesEquals(Programme expected, Programme actual) {
        assertProgrammeUpdatableFieldsEquals(expected, actual);
        assertProgrammeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgrammeAutoGeneratedPropertiesEquals(Programme expected, Programme actual) {
        assertThat(actual)
            .as("Verify Programme auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgrammeUpdatableFieldsEquals(Programme expected, Programme actual) {
        assertThat(actual)
            .as("Verify Programme relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getCodeProgramme()).as("check codeProgramme").isEqualTo(expected.getCodeProgramme()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProgrammeUpdatableRelationshipsEquals(Programme expected, Programme actual) {
        // empty method
    }
}
