package sn.edu.ugb.curriculum.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UEAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUEAllPropertiesEquals(UE expected, UE actual) {
        assertUEAutoGeneratedPropertiesEquals(expected, actual);
        assertUEAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUEAllUpdatablePropertiesEquals(UE expected, UE actual) {
        assertUEUpdatableFieldsEquals(expected, actual);
        assertUEUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUEAutoGeneratedPropertiesEquals(UE expected, UE actual) {
        assertThat(actual)
            .as("Verify UE auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUEUpdatableFieldsEquals(UE expected, UE actual) {
        assertThat(actual)
            .as("Verify UE relevant properties")
            .satisfies(a -> assertThat(a.getIntitule()).as("check intitule").isEqualTo(expected.getIntitule()))
            .satisfies(a -> assertThat(a.getCredits()).as("check credits").isEqualTo(expected.getCredits()))
            .satisfies(a -> assertThat(a.getNiveauId()).as("check niveauId").isEqualTo(expected.getNiveauId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUEUpdatableRelationshipsEquals(UE expected, UE actual) {
        // empty method
    }
}
